### PR TITLE
Simplified quickstart

### PR DESCRIPTION
**Pull request by 200sc**

### CODE REVIEW

**Comment by 200sc** [comment]
The terraform version requirements are really strict-- 0.12.20 is too old, somewhere between that and 0.12.30 it starts working:
```

**Comment by 200sc** [comment]
`

**Comment by 200sc** [comment]
Due to a recent change in the server, we get this error on init: 
```
Error: cannot create Resource: failed to override driver-specific config: invalid operation: TLS certificates must be generated before creating website resources

  on .terraform/modules/strongdm_onboarding/create_http_website.tf line 86, in resource "sdm_resource" "web_page":
  86: resource "sdm_resource" "web_page" {
```

You currently can't generate web certs from terraform, we are leaning towards just generating certs for orgs when they verify their email.

**Comment by jeffreylees** [comment]
>You currently can't generate web certs from terraform, we are leaning towards just generating certs for orgs when they verify their email.

Should we remove the http creation for now then?

**Comment by jeffreylees** [comment]
> The terraform version requirements are really strict-- 0.12.20 is too old, somewhere between that and 0.12.30 it starts working:
> 
> ```
> Module vpc (from "terraform-aws-modules/vpc/aws") does not support Terraform
> version 0.12.20. To proceed, either choose another supported Terraform version
> or update the module's version constraint. Version constraints are normally
> set for good reason, so updating the constraint may lead to other errors or
> unexpected behavior.
> ```
> 
> And it also probably stops working at 0.13:
> 
> ```
> Warning: registry.terraform.io: For users on Terraform 0.13 or greater, this provider has moved to strongdm/sdm. Please update your source in required_providers.
> ```
> 
> It would be really nice if we could support 13 and 14, but I don't know how much work that would involve.

OK, so for now should we say 12.30 and up, but 13+ is not yet supported? And then dig into what v13 support would take as a separate issue?

**Comment by 200sc** [comment]
We're going to look into how hard it is to support terraform 13 for a second in our testing

**Comment by etodd** [comment]
The module has been updated to work with both Terraform 12 and 13! 🥳

**Pull request merged**
